apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: sourav0112/booking-service:v1.1
          imagePullPolicy: IfNotPresent
          # command: ["sleep", "3600"]
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: MONGO_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: PORT

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
