apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking
spec:
  selector:
    app: booking-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
   #  nodePort: 30000
