apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: booking
type: Opaque
stringData:
  MONGO_URL: mongodb+srv://sourav:chaudhary@cluster0.5wbresh.mongodb.net/Nestjs-callbooking?retryWrites=true&w=majority
  PORT: "8001"
