version: "3.8" 

services:
  booking-service:
    image: sourav01112/booking-service:latest
    container_name: nestjs-booking-service
    build:
      context: .
      dockerfile: ./apps/booking-service/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/src:cached
    environment:
      - MONGO_URL=mongodb+srv://sourav:chaudhary@cluster0.5wbresh.mongodb.net/?retryWrites=true&w=majority/Nestjs-callbooking
      - PORT=8001
    networks:
      - nestjs-monrepo

  admin-service:
    image: sourav01112/admin-service:latest
    container_name: nestjs-admin-service
    build:
      context: .
      dockerfile: ./apps/admin-service/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - .:/src:cached
    environment:
      - MONGO_URL=mongodb+srv://sourav:chaudhary@cluster0.5wbresh.mongodb.net/?retryWrites=true&w=majority/Nestjs-callbooking
      - PORT=8002
    networks:
      - nestjs-monrepo


networks:
  nestjs-monrepo:
    driver: bridge
